name: CI

on:
  push:
    branches: [master]
  pull_request:


defaults:
  run:
    shell: bash

jobs:

  build-and-test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
            go_arch: amd64
          - os: ubuntu-latest
            rust_target: aarch64-unknown-linux-gnu
            go_arch: arm64
          - os: macos-latest
            rust_target: x86_64-apple-darwin
            go_arch: amd64
          - os: macos-latest
            rust_target: aarch64-apple-darwin
            go_arch: arm64
          - os: windows-latest
            rust_target: x86_64-pc-windows-gnu
            go_arch: amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: rustup update
      - run: rustup target add ${{ matrix.rust_target }}
      # Set cross compiler for linux aarch64
      - if: matrix.rust_target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update 
          sudo apt-get install -y gcc-9-aarch64-linux-gnu
          echo 'CC=aarch64-linux-gnu-gcc' >> $GITHUB_ENV
      - run: CGO_ENABLED=1 CARGO_BUILD_TARGET=${{ matrix.rust_target }} GOARCH=${{ matrix.go_arch }} make main
      # Show the executable size and file type
      - run: ls -lh main && file main
      # We can run it in all platforms except arm, which is cross-compiled
      - if: matrix.go_arch != 'arm64'
        run: ./main
