name: CI

on:
  push:
    branches: [master]
  pull_request:


defaults:
  run:
    shell: bash

jobs:

  build-and-test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
            go_arch: amd64
          # TODO: fix Linux ARM cross-compilation
          #       last failure seen at https://github.com/2opremio/rust-plus-golang/actions/runs/3422673800/jobs/5700353279
          #- os: ubuntu-latest
          #  rust_target: aarch64-unknown-linux-gnu
          #  go_arch: arm64
          - os: macos-latest
            rust_target: x86_64-apple-darwin
            go_arch: amd64
          - os: macos-latest
            rust_target: aarch64-apple-darwin
            go_arch: arm64
          - os: windows-latest
            rust_target: x86_64-pc-windows-gnu
            go_arch: amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: rustup update
      - run: rustup target add ${{ matrix.rust_target }}
      - run: CGO_ENABLED=1 CARGO_BUILD_TARGET=${{ matrix.rust_target }} GOARCH=${{ matrix.go_arch }} make main
      # show the executable size and file type
      - run: ls -lh main && file main
      # We can run it in all platforms except arm, which is cross-compiled
      - if: matrix.go_arch != 'arm64'
        run: ./main
